import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  Lexend,
  Lora,
  IBM_Plex_Sans,
  Xanh_Mono,
  Inter,
} from "next/font/google";

import "./globals.css";
import { Providers } from "@/redux/provider";
import Footer from "@/components/Footer";
import TopBanner from "@/components/layout/TopBanner";
import Header from "@/components/Header";

const poppinsVN = localFont({
  src: "./fonts/Poppins-Light.otf",
  display: "swap",
  variable: "--font-poppins",
});
const poppinsVN_Medium = localFont({
  src: "./fonts/Poppins-Medium.otf",
  display: "swap",
  variable: "--font-poppins-medium",
});
const poppinsVN_Bold = localFont({
  src: "./fonts/Poppins-Bold.otf",
  display: "swap",
  variable: "--font-poppins-bold",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});
const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
  display: "swap",
});
const xanh_mono = Xanh_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-xanh-mono",
  display: "swap",
});
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Hoàng Tuấn Anh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <div className="min-h-screen relative bg-gradient-to-tl from-zinc-900 via-zinc-400/10 to-zinc-900 bg-no-repeat">
          <Providers>
            {/* <TopBanner /> */}
            <Header />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
