import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lexend, Lora, IBM_Plex_Sans, Xanh_Mono } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "@/redux/provider";
import Footer from "@/components/Footer";
import TopBanner from "@/components/layout/TopBanner";

const poppinsVN = localFont({
  src: "./Poppins-Light.otf",
  display: "swap",
  variable: "--font-poppins",
});
const poppinsVN_Medium = localFont({
  src: "./Poppins-Medium.otf",
  display: "swap",
  variable: "--font-poppins-medium",
});
const poppinsVN_Bold = localFont({
  src: "./Poppins-Bold.otf",
  display: "swap",
  variable: "--font-poppins-bold",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});
const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});
const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
  display: "swap",
});
const xanh_mono = Xanh_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-xanh-mono",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Hoàng Tuấn Anh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsVN.variable} ${poppinsVN_Bold.variable} ${poppinsVN_Medium.variable} ${ibm_plex_sans.variable} ${lora.variable} ${lexend.variable} ${xanh_mono.variable} font-lexend text-base leading-[22.4px]`}
      >
        <Providers>
          <TopBanner />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
