import type { Metadata } from "next";
import { Lexend, Lora, IBM_Plex_Sans, Xanh_Mono } from "next/font/google";
import "../globals.css";
import RightSidebar from "@/components/layout/RightSidebar";
import LeftSidebar from "@/components/layout/LeftSidebar";
export const metadata: Metadata = {
  title: "Hoàng Tuấn Anh",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex justify-between gap-x-[60px]">
        <div className="w-[15%]">
          <LeftSidebar />
        </div>
        <div className="w-[57%]">{children}</div>
        <div className="w-[19%]">
          <RightSidebar />
        </div>
      </div>
    </>
  );
}
